import re

seq1 = "TACATATTACCTATTACCTATTACCTATTACCGCATATTACCTGTATTACCTATTACCTATTACCTTATTACCCTATTACCATATTACCCCGCTTTATTACCTTTTATTACCGCCGTAGCGTATTACCATTCCCGAAATATTACCTTATTACCTTATTACCTATTACCTATTACCTATTACCTATTACCTATTACCTATTACCGATTGATTATTACCTATTACCATGTCTATTACCTATTACCAATATTACCTCTTATTACCGGAGATATTACCTATTACCCCGTATTACCTATTACCAATCTATTACCCCGCATATTACCTTGTTATTACCTTATTACCCGTATTACCCGAGATATTACCAGGATATATTACCTATTACCGTATTACCTTTGTTGATCGTGTATTACCAATACCTATTACCTATTACCAGGTTTATTACCTATTACCTACTATTACCCATATTACCCTATTACCTATTACCCCACGGGTGATTATTACCAGCATATTACCTGTATTACCCCGTATTACCTATTACCCTATTACCGTATTACCTATTACCTTATTACCGTATTACCATATTACCAATTATTACCCTATTACCATACGTATTACCTATTACCTCCTCCCGTATTACCTAATATTACCATATTACCCAGTTATTACCCCCGTTCTATTACCATATTACCTATTACCTATTACCGATATTACCGCGTATTACCCTTATTACCGTTATTACCAGCTTGTATTACCGATATTACCTGATATTACCGCATATTACCAGTATTACCAGATATTACCGTATTACCAAGCTTATTACCCCGCATATTACCACATGTATTACCTTATTACCGCTATTACCAAGTGTTATTACCGTCTGGTGTAACAGGGCGTTCGGCTATATTACCGAGTATTACCTATTACCATATTACCGTATTACCTTATTACCTATTACCGTCTATTACC"

match = re.finditer("(?=TATTACCTA)", seq1)
list = []
n = 0 
for m in match:

    list.insert(n, int(m.start()))
    list[n] += 1 
    n += 1

string1 = re.sub(",", "", str(list)[1:-1])

print(string1)    